version: "3"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - .:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - "9000:3306"
        environment:
            MYSQL_DATABASE: empreendorismo_site
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./database:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
# volumes:
    # persistent:
